id: P009156
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:25:41.288115
source_metadata:
  id: bdr:W30518
  title: རྒྱུན་སྤྱོད་བོད་སྨན་ལག་དེབ།
  author: ''
  volumes:
    bc6f5f72f6eb4a91ab9905118ebc6137:
      image_group_id: I1KG21739
      title: ''
      volume_number: 1
      total_pages: 120
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
