id: I49F4EDA8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:57:17+00:00'
last_modified: '2022-06-08T09:01:13.714396+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30518
  title: རྒྱུན་སྤྱོད་བོད་སྨན་ལག་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F7D0:
      image_group_id: I1KG21739
      title: ''
      total_pages: 120
      order: 1
      base_file: F7D0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
